import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:dio/dio.dart';
import 'package:cached_network_image/cached_network_image.dart';

import 'package:agentichr_frontend/domain/providers/providers.dart';

class BrandingManagementScreen extends ConsumerStatefulWidget {
  const BrandingManagementScreen({super.key});

  @override
  ConsumerState<BrandingManagementScreen> createState() =>
      _BrandingManagementScreenState();
}

class _BrandingManagementScreenState
    extends ConsumerState<BrandingManagementScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  String _templateType = 'HIRING';
  XFile? _selectedFile;
  bool _isUploading = false;

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final image = await picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      setState(() {
        _selectedFile = image;
      });
    }
  }

  Future<void> _uploadTemplate() async {
    if (!_formKey.currentState!.validate() || _selectedFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content: Text('Please fill all fields and select an image')),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      final repository = ref.read(brandingRepositoryProvider);
      final bytes = await _selectedFile!.readAsBytes();
      final multipartFile = MultipartFile.fromBytes(
        bytes,
        filename: _selectedFile!.name,
      );

      final result = await repository.uploadTemplate(
        name: _nameController.text,
        type: _templateType,
        file: multipartFile,
      );

      _nameController.clear();
      final previewUrl = result['preview_url'];

      setState(() {
        _selectedFile = null;
      });

      ref.invalidate(brandingTemplatesProvider(null));

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
              content: Text('Template uploaded and style analyzed!')),
        );

        if (previewUrl != null) {
          _showPreviewDialog(previewUrl, isAI: true);
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Upload failed: $e')),
        );
      }
    } finally {
      setState(() {
        _isUploading = false;
      });
    }
  }

  Future<void> _checkSample(String templateId) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      final repository = ref.read(brandingRepositoryProvider);
      final previewUrl = await repository.getPreview(templateId, {
        'title': 'Senior Flutter Developer',
        'highlights': [
          '5+ Years Experience',
          'Dart & Riverpod Expert',
          'Remote Friendly'
        ],
        'candidate_name': 'John Doe (Sample)',
      });

      if (mounted) {
        Navigator.pop(context); // Close loading
        _showPreviewDialog(previewUrl, isAI: false);
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Preview failed: $e')),
        );
      }
    }
  }

  Future<void> _checkAISample(String templateId) async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      final repository = ref.read(brandingRepositoryProvider);
      final previewUrl = await repository.getAIPreview(templateId);

      if (mounted) {
        Navigator.pop(context); // Close loading
        _showPreviewDialog(previewUrl, isAI: true);
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('AI Preview failed: $e')),
        );
      }
    }
  }

  void _showPreviewDialog(String previewUrl, {bool isAI = false}) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(isAI ? 'AI Sample Preview' : 'Sample Preview'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(isAI ? 'Content generated by AI:' : 'Sample data used:'),
            const SizedBox(height: 8),
            Text(
                isAI
                    ? '- Realistically generated title and points\n- Dynamic font sizing\n- Automated contrast detection'
                    : '- Hardcoded sample data\n- Dynamic font sizing\n- Automated contrast detection',
                style: const TextStyle(fontSize: 12, color: Colors.grey)),
            const SizedBox(height: 16),
            ClipRRect(
              borderRadius: BorderRadius.circular(8),
              child: CachedNetworkImage(
                imageUrl: 'http://localhost:8000$previewUrl',
                placeholder: (context, url) =>
                    const CircularProgressIndicator(),
                errorWidget: (context, url, error) => const Icon(Icons.error),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final templatesAsync = ref.watch(brandingTemplatesProvider(null));

    return Scaffold(
      appBar: AppBar(
        title: const Text('Branding Management'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Upload Form
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Text('Upload New Template',
                          style: Theme.of(context).textTheme.titleLarge),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _nameController,
                        decoration:
                            const InputDecoration(labelText: 'Template Name'),
                        validator: (v) =>
                            v?.isEmpty ?? true ? 'Required' : null,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        initialValue: _templateType,
                        decoration:
                            const InputDecoration(labelText: 'Template Type'),
                        items: const [
                          DropdownMenuItem(
                              value: 'HIRING', child: Text('Hiring Post')),
                          DropdownMenuItem(
                              value: 'WELCOME',
                              child: Text('Welcome/Joiner Post')),
                        ],
                        onChanged: (v) => setState(() => _templateType = v!),
                      ),
                      const SizedBox(height: 16),
                      OutlinedButton.icon(
                        onPressed: _pickImage,
                        icon: const Icon(Icons.image),
                        label: Text(_selectedFile == null
                            ? 'Select Image'
                            : 'Change Image (${_selectedFile!.name})'),
                      ),
                      const SizedBox(height: 16),
                      ElevatedButton(
                        onPressed: _isUploading ? null : _uploadTemplate,
                        child: _isUploading
                            ? const SizedBox(
                                height: 20,
                                width: 20,
                                child:
                                    CircularProgressIndicator(strokeWidth: 2))
                            : const Text('Upload Template'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(height: 32),

            // Templates List
            Text('Existing Templates',
                style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 16),
            templatesAsync.when(
              data: (templates) => ListView.separated(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: templates.length,
                separatorBuilder: (context, index) =>
                    const SizedBox(height: 12),
                itemBuilder: (context, index) {
                  final t = templates[index];
                  return Card(
                    child: ListTile(
                      leading: const Icon(Icons.branding_watermark),
                      title: Text(t['name'] ?? 'Untitled'),
                      subtitle: Text(t['template_type'] ?? 'HIRING'),
                      trailing: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          TextButton.icon(
                            onPressed: () => _checkSample(t['id']),
                            icon: const Icon(Icons.remove_red_eye_outlined),
                            label: const Text('Sample'),
                          ),
                          TextButton.icon(
                            onPressed: () => _checkAISample(t['id']),
                            icon: const Icon(Icons.auto_awesome_outlined),
                            label: const Text('AI Sample'),
                          ),
                          IconButton(
                            icon: const Icon(Icons.delete_outline,
                                color: Colors.red),
                            onPressed: () async {
                              await ref
                                  .read(brandingRepositoryProvider)
                                  .deleteTemplate(t['id']);
                              ref.invalidate(brandingTemplatesProvider(null));
                            },
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, s) => Text('Error: $e'),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }
}
